#!/bin/sh

#set -e

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
	configure)
		# autostart?
		db_get nipap-whoisd/startup
		if [ "$RET" = "true" ]; then
			sed -i -e 's/RUN=.*/RUN=yes/' /etc/default/nipap-whoisd
			deb-systemd-helper enable nipap-whoisd.service >/dev/null
		else
			sed -i -e 's/RUN=.*/RUN=no/' /etc/default/nipap-whoisd
			deb-systemd-helper disable nipap-whoisd.service >/dev/null
		fi
	;;
esac

#DEBHELPER#

exit 0
